from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_ROOT = ROOT / "docs" / "cases" / "generated"
CANONICAL_SCENARIOS = (
    "incident-investigation",
    "bringup-path",
    "design-safety-review",
)
TEMPLATE_SPECS = (
    ("01-skill-routing-matrix.md", ROOT / "docs" / "templates" / "skill-routing-matrix.md"),
    ("02-orchestrator-dispatch-plan.md", ROOT / "docs" / "templates" / "orchestrator-dispatch-plan.md"),
    ("03-incident-summary.md", ROOT / "docs" / "templates" / "incident-summary.md"),
    ("04-evidence-package.md", ROOT / "docs" / "templates" / "evidence-package.md"),
    ("05-incident-diagnosis-pack.md", ROOT / "docs" / "templates" / "incident-diagnosis-pack.md"),
    ("06-incident-review-memo.md", ROOT / "docs" / "templates" / "incident-review-memo.md"),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a reusable incident-workflow document bundle from un9flow templates."
    )
    parser.add_argument("case_id", help="Stable case id used to name the generated bundle.")
    parser.add_argument(
        "--title",
        default=None,
        help="Human-readable case title. Defaults to the case id.",
    )
    parser.add_argument(
        "--scenario",
        choices=CANONICAL_SCENARIOS,
        default="incident-investigation",
        help="Primary scenario for the generated bundle.",
    )
    parser.add_argument(
        "--output-root",
        default=str(DEFAULT_OUTPUT_ROOT),
        help="Root directory that will contain the generated case bundle.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing generated bundle directory.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the files that would be generated without writing them.",
    )
    return parser.parse_args()


def bundle_dir(output_root: Path, case_id: str) -> Path:
    return output_root / case_id


def build_bundle_readme(case_id: str, title: str, scenario: str) -> str:
    ordered_files = "\n".join(f"- `{filename}`" for filename, _ in TEMPLATE_SPECS)
    return (
        "# generated-incident-case-bundle\n\n"
        f"- case id: `{case_id}`\n"
        f"- case title: `{title}`\n"
        f"- primary scenario: `{scenario}`\n"
        "- generated by: `tools/generate_incident_case_bundle.py`\n"
        "- generation rule: preserve un9flow template order for route -> dispatch -> artifacts -> review\n\n"
        "## bundle files\n"
        f"{ordered_files}\n"
    )


def inject_metadata(template_text: str, case_id: str, title: str, scenario: str, source_label: str) -> str:
    metadata_lines = [
        f"- case id: `{case_id}`",
        f"- case title: `{title}`",
        f"- primary scenario: `{scenario}`",
        f"- generated from: `{source_label}`",
        "- generated by: `tools/generate_incident_case_bundle.py`",
    ]
    lines = template_text.splitlines()
    if lines and lines[0].startswith("#"):
        return "\n".join([lines[0], "", *metadata_lines, "", *lines[1:]]) + "\n"
    return "\n".join([*metadata_lines, "", *lines]) + "\n"


def ensure_writable_target(target_dir: Path, force: bool) -> None:
    if not target_dir.exists():
        return
    if not force:
        raise FileExistsError(
            f"Target directory already exists: {target_dir}. Pass --force to overwrite it."
        )
    shutil.rmtree(target_dir)


def render_bundle(case_id: str, title: str, scenario: str, output_root: Path, force: bool, dry_run: bool) -> int:
    target_dir = bundle_dir(output_root, case_id)
    planned_files = ["README.md", *(filename for filename, _ in TEMPLATE_SPECS)]

    if dry_run:
        print(f"Dry run bundle root: {target_dir}")
        for filename in planned_files:
            print(f"- {target_dir / filename}")
        return 0

    ensure_writable_target(target_dir, force)
    target_dir.mkdir(parents=True, exist_ok=True)

    (target_dir / "README.md").write_text(
        build_bundle_readme(case_id=case_id, title=title, scenario=scenario),
        encoding="utf-8",
    )

    for filename, template_path in TEMPLATE_SPECS:
        template_text = template_path.read_text(encoding="utf-8")
        source_label = template_path.relative_to(ROOT).as_posix()
        rendered_text = inject_metadata(
            template_text=template_text,
            case_id=case_id,
            title=title,
            scenario=scenario,
            source_label=source_label,
        )
        (target_dir / filename).write_text(rendered_text, encoding="utf-8")

    print(f"Generated incident case bundle: {target_dir}")
    for filename in planned_files:
        print(f"- {target_dir / filename}")
    return 0


def main() -> int:
    args = parse_args()
    case_id = args.case_id.strip()
    if not case_id:
        print("case_id must not be empty.", file=sys.stderr)
        return 2

    title = args.title.strip() if args.title else case_id
    output_root = Path(args.output_root)

    try:
        return render_bundle(
            case_id=case_id,
            title=title,
            scenario=args.scenario,
            output_root=output_root,
            force=args.force,
            dry_run=args.dry_run,
        )
    except FileExistsError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    except OSError as exc:
        print(f"Failed to generate bundle: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
